{
 "title": "ArgoCD",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(argocd_app_health_status, exported_namespace)"
   },
   {
    "name": "project",
    "query": "label_values(argocd_app_health_status, project)"
   }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=200&v=4)   "
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Applications Deployed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "content": "#### Health Status:" },
  {
   "title": "Healthy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_health_status{health_status=\"Healthy\",namespace=~\"$namespace\",project=~\"$project\"} == 1)"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_health_status{health_status=\"Progressing\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Suspended",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_health_status{health_status=\"Suspended\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Degraded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_health_status{health_status=\"Degraded\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_health_status{health_status=\"Missing\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_health_status{health_status=\"Unknown\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 }, "content": "#### Sync Status:" },
  {
   "title": "Synced",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_sync_status{sync_status=\"Synced\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "OutOfSync",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_sync_status{sync_status=\"OutOfSync\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_sync_status{sync_status=\"Unknown\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sync Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_sync_total{namespace=~\"$namespace\",project=~\"$project\"}[5m])) by (phase)"
    }
   ]
  },
  {
   "title": "Reconciliation Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",project=~\"$project\"}[10m]))"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\",project=~\"$project\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Server Stats:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"argocd-server-metrics\", quantile=\"1\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 }, "content": "#### gRPC Services:" },
  {
   "title": "grpc service ApplicationService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"application.ApplicationService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service ClusterService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"cluster.ClusterService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service ProjectService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"project.ProjectService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service RepositoryService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"repository.RepositoryService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service SessionService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"session.SessionService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service VersionService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"version.VersionService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service AccountService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"account.AccountService\",namespace=~\"$namespace\"} >1",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  { "title": "Repo Server Stats:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-repo-server\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-repo-server\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}